# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_diary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Diary(object):
    def setupUi(self, Diary):
        Diary.setObjectName("Diary")
        Diary.resize(600, 450)
        Diary.setMinimumSize(QtCore.QSize(600, 450))
        Diary.setMaximumSize(QtCore.QSize(600, 450))
        self.plainTextEdit_diary = QtWidgets.QPlainTextEdit(Diary)
        self.plainTextEdit_diary.setGeometry(QtCore.QRect(10, 10, 581, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_diary.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_diary.setSizePolicy(sizePolicy)
        self.plainTextEdit_diary.setMinimumSize(QtCore.QSize(200, 30))
        self.plainTextEdit_diary.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setFamily("方正喵呜体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_diary.setFont(font)
        self.plainTextEdit_diary.setAcceptDrops(True)
        self.plainTextEdit_diary.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_diary.setObjectName("plainTextEdit_diary")
        self.commandLinkButton_save = QtWidgets.QCommandLinkButton(Diary)
        self.commandLinkButton_save.setGeometry(QtCore.QRect(20, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.commandLinkButton_save.setFont(font)
        self.commandLinkButton_save.setObjectName("commandLinkButton_save")
        self.commandLinkButton_save_and_exit = QtWidgets.QCommandLinkButton(Diary)
        self.commandLinkButton_save_and_exit.setGeometry(QtCore.QRect(420, 400, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.commandLinkButton_save_and_exit.setFont(font)
        self.commandLinkButton_save_and_exit.setObjectName("commandLinkButton_save_and_exit")

        self.retranslateUi(Diary)
        QtCore.QMetaObject.connectSlotsByName(Diary)

    def retranslateUi(self, Diary):
        _translate = QtCore.QCoreApplication.translate
        Diary.setWindowTitle(_translate("Diary", "日记"))
        self.plainTextEdit_diary.setToolTip(_translate("Diary", "在这里输入日记"))
        self.plainTextEdit_diary.setStatusTip(_translate("Diary", "在这里输入日记"))
        self.plainTextEdit_diary.setPlainText(_translate("Diary", "在这里记录你的每一天"))
        self.commandLinkButton_save.setText(_translate("Diary", "保存"))
        self.commandLinkButton_save_and_exit.setText(_translate("Diary", "保存并退出"))
